### ISSUE TITLE
How to connect?

### ISSUE THREAD

**Issue by ArpitPy** [TwentyFiveSoftware/typerace-server#8]
How to connect this code to frontend?

**Comment by TwentyFiveSoftware** [comment]
In the [frontend project](https://github.com/TwentyFiveSoftware/typerace) is a `.env.dist` file that you have to copy and save as `.env`. This file sets an environment variable called `VITE_SOCKET_ENDPOINT`, which specifies the url of the backend that the frontend should use. For example, to use the backend server running locally on your machine (after starting this project), just set this environment variable to `localhost:5000`.
